services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=pratik_ecommerce_project
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data: 